### ISSUE TITLE
Need to loop to read all the puzzles in the input file

### ISSUE THREAD

**Issue by Digitaliss** [cluckcluck22/Comp472FinalProject#12]
Not sure where this loop should be, but we can't have the program end until all the puzzles have been played and solved.
For now, I am going to try making the Board State Handler keep pulling until the File Handler says there is no more boards left. However, the Manual Input Handler will also have to change for this to work.
PS. Not sure this is how one is supposed to be writing issues. CCW.

**Comment by cluckcluck22** [comment]
Ok I can modify the manual input handler to handle the checks, and if i need something else I will modify the board if i need something like a has next file.

**Comment by cluckcluck22** [comment]
Should be fixed now. Needs to be tested to work properly.
